### ISSUE TITLE
Rmd documents are not uniform

### ISSUE THREAD

**Issue by idc9** [idc9/stor390#11]
The headings for all the .Rmd documents are not the same, in particular the headers should look like

```
---
title: "**More classification**"
subtitle: "SVM, kernels, classification metrics"
author: "[STOR 390](https://idc9.github.io/stor390/)"
output:
  html_document:
    theme: cosmo
    toc: yes
    toc_float: yes
---
```

I.e. title, subtitle, author pointing to the webpage, and a floating table of contents. This is most important for the notes. The headers for the assignments/labs should be the same but without the table of contents.
